name: CI/CD with Node + Python

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python Virtual Environment
      run: |
        if [ ! -d "venv" ]; then
          python3 -m venv venv
        fi
        
        source venv/bin/activate
        pip install --upgrade pip

    - name: Install Node.js Dependencies
      run: |
        source venv/bin/activate
        cd Backend
        pip install -r requirements.txt
        npm install
        echo "${{ secrets.BACKEND_ENV }}" > .env

    - name: Restart App with PM2
      run: |
        cd Backend
        pm2 restart mockapp
